Repository CSE-210-Team-11/cse210-fa24-group-11, pull requests merged in 2024-12, with the labels that each got.

#85 Deleting files related to streak reset (No longer in use). #83
  src/__tests__/components/streak/streakIcon.html.test.js
  src/__tests__/scripts/task_page.test.js
  src/__tests__/styles/components/streak/streak.css.test.js
  src/__tests__/styles/pages/task_page.css.test.js
  src/components/streak/streak.svg
  src/components/streak/streakIcon.html
  src/components/streak/streakRecordButton.html
  src/components/streak/unStreak.svg
  src/styles/components/streak/streak.css
  src/styles/pages/task_page.css
Labels: improvements

#126 Improve the CD and redirect index.html to home.html
  .github/workflows/static.yml
  src/index.html
  src/index.js
Labels: enhancement

#129 Fixed cd dependencies issue
  .github/workflows/static.yml
Labels: bug

#139 Update Guidelines.md
  docs/Guidelines.md
Labels: documentation

#140 Add files via upload
  .github/404.html
Labels: enhancement

#142 Update cicd.md
  docs/cicd.md
Labels: documentation

#148 Fix 404 not redirect
  .github/workflows/static.yml
Labels: bug

#151 Handle redirect to 404 page globally
  .github/404.html
Labels: bug

#152 Update README.md
  README.md
Labels: documentation

#144 Update diagramSrc.md
  docs/diagramSrc.md
Labels: documentation

#147 Rename diagramSrcBkup.md to Project_Flowchart-1.md
  docs/Project_Flowchart-1.md
Labels: documentation

#157 Sprint-1-review restructuring
  admin/meetings/111824-sprint-1-review.md
Labels: documentation

#162 Adding birds.
  src/pages/home.html
  src/pages/project-list.html
  src/styles/components/streak/birds.css
  src/styles/pages/task-page.css
Labels: enhancement

#164 Update flow-chart in CICD file
  docs/cicd.md
Labels: documentation

#180 Documentgeneration and readme file update
  README.md
  docs/jsdoc/fonts/OpenSans-Bold-webfont.eot
  docs/jsdoc/fonts/OpenSans-Bold-webfont.svg
  docs/jsdoc/fonts/OpenSans-Bold-webfont.woff
  docs/jsdoc/fonts/OpenSans-BoldItalic-webfont.eot
  docs/jsdoc/fonts/OpenSans-BoldItalic-webfont.svg
  docs/jsdoc/fonts/OpenSans-BoldItalic-webfont.woff
  docs/jsdoc/fonts/OpenSans-Italic-webfont.eot
  docs/jsdoc/fonts/OpenSans-Italic-webfont.svg
  docs/jsdoc/fonts/OpenSans-Italic-webfont.woff
  docs/jsdoc/fonts/OpenSans-Light-webfont.eot
  docs/jsdoc/fonts/OpenSans-Light-webfont.svg
  docs/jsdoc/fonts/OpenSans-Light-webfont.woff
  docs/jsdoc/fonts/OpenSans-LightItalic-webfont.eot
  docs/jsdoc/fonts/OpenSans-LightItalic-webfont.svg
  docs/jsdoc/fonts/OpenSans-LightItalic-webfont.woff
  docs/jsdoc/fonts/OpenSans-Regular-webfont.eot
  docs/jsdoc/fonts/OpenSans-Regular-webfont.svg
  docs/jsdoc/fonts/OpenSans-Regular-webfont.woff
  docs/jsdoc/global.html
  docs/jsdoc/index.html
  docs/jsdoc/module-404.html
  docs/jsdoc/module-motivationalQuotes.html
  docs/jsdoc/module-projectLoader.html
  docs/jsdoc/scripts/linenumber.js
  docs/jsdoc/scripts/prettify/Apache-License-2.0.txt
  docs/jsdoc/scripts/prettify/lang-css.js
  docs/jsdoc/scripts/prettify/prettify.js
  docs/jsdoc/scripts_404.js.html
  docs/jsdoc/scripts_circlevisualisation.js.html
  docs/jsdoc/scripts_components_streak_displayStreak.js.html
  docs/jsdoc/scripts_components_streak_streak.js.html
  docs/jsdoc/scripts_components_tree_tree.js.html
  docs/jsdoc/scripts_projectLoader.js.html
  docs/jsdoc/scripts_quote.js.html
  docs/jsdoc/scripts_quotesmanager.js.html
  docs/jsdoc/scripts_taskflow.js.html
  docs/jsdoc/styles/jsdoc-default.css
  docs/jsdoc/styles/prettify-jsdoc.css
  docs/jsdoc/styles/prettify-tomorrow.css
  docs/jsdoc/utils_seededRandom.js.html
  docs/jsdoc/utils_timeOfDay.js.html
  jsdoc.json
  package-lock.json
  package.json
Labels: documentation

#181 whatsapp_report generation analysis
  admin/meetings/Whatsapp-report.md
Labels: documentation

#182 Update README.md
  README.md
Labels: documentation
