Repository CSE-210-Team-11/cse210-fa24-group-11, pull requests merged in 2024-11, with the labels that each got.

#4 Generating ADR for proposed code quality tool - Biome.
  admin/adr/0002-use-biome-for-code-quality.md
Labels: documentation

#15 ADR to generate documentation using JS Doc
  README.md
  admin/adr/0003-use-jsdoc-for-documentation.md
Labels: documentation

#19 Add CI workflow with Node.js setup and test automation
  .github/workflows/CI.yml
Labels: enhancement

#69 Add ES6 style Jest+JSDOM testing env
  babel.config.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
Labels: test
